package com.charbel.backend.repo;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.charbel.backend.DTO.ChildPercentView;
import com.charbel.backend.DTO.DeltaTransactions;
import com.charbel.backend.DTO.ParentSpendView;
import com.charbel.backend.DTO.PercentGap;
import com.charbel.backend.DTO.StatisticsViews;
import com.charbel.backend.model.CategoryType;
import com.charbel.backend.model.Transaction;
import com.charbel.backend.model.Users;

@Repository
public interface TransactionRepo extends JpaRepository<Transaction, Long> {
    Optional<Transaction> findByIdAndUser(Long id, Users user);

    @Query("""
            select t from Transaction t
            join fetch t.category c
            left join fetch c.parent p
            where t.user = :user
            order by t.transactionDate desc
            """)
    List<Transaction> findByUserOrderByTransactionDateDesc(@Param("user") Users user);

    @Query("""
            SELECT COALESCE(SUM(t.amount), 0)
            FROM Transaction t
            WHERE t.user = :user
            AND t.transactionDate >= :start
            AND t.transactionDate < :end
            AND t.category.type = :type
            """)
    BigDecimal sumByUserAndMonthYearAndType(Users user, LocalDate start, LocalDate end, CategoryType type);

    @Query(value="""
            SELECT CASE WHEN REVENU + B.AMOUNT = 0 THEN 0 ELSE ROUND(DEPENSE/(REVENU+B.AMOUNT)*100,0) END PERCENT
            FROM (SELECT COALESCE(SUM(CASE WHEN TYPE = 'DEPENSE' THEN T.AMOUNT ELSE 0 END), 0) AS DEPENSE, COALESCE(SUM(CASE WHEN TYPE = 'REVENU' THEN T.AMOUNT ELSE 0 END), 0) AS REVENU, T.USER_ID
            FROM WISE_MONEY.TRANSACTIONS T
            INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
            WHERE T.USER_ID = :userId AND EXTRACT(MONTH FROM SYSDATE()) = EXTRACT(MONTH FROM T.TRANSACTION_DATE)
            AND EXTRACT(YEAR FROM SYSDATE()) = EXTRACT(YEAR FROM T.TRANSACTION_DATE)
            GROUP BY T.USER_ID) SUB
            INNER JOIN WISE_MONEY.BUDGETS B ON B.USER_ID = SUB.USER_ID
            WHERE EXTRACT(MONTH FROM SYSDATE()) = MONTH
            AND EXTRACT(YEAR FROM SYSDATE()) = YEAR
            """, nativeQuery = true)
    Integer findCurrentMonthPercentByUserId(@Param("userId") Long userId);

    @Query(value="""
                WITH BUDGET AS (SELECT USER_ID, AMOUNT FROM WISE_MONEY.BUDGETS
                WHERE USER_ID = :userId AND MONTH = EXTRACT(MONTH FROM SYSDATE()) AND YEAR = EXTRACT(YEAR FROM SYSDATE())),
                REVENU AS (SELECT T.USER_ID, SUM(AMOUNT) AS TR
                FROM WISE_MONEY.TRANSACTIONS T
                INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
                WHERE T.USER_ID = :userId
                AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                AND C.TYPE = 'REVENU'
                GROUP BY USER_ID),
                DEPENSES_LBP AS (SELECT BM.USER_ID, SUM(T.AMOUNT) AS TD FROM WISE_MONEY.TRANSACTIONS T
                INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
                WHERE BM.AMOUNT = 0
                AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                GROUP BY BM.USER_ID),
                TOTAL_EXCES AS (SELECT USER_ID, SUM(T_AMOUNT - AMOUNT) AS TOTAL
                FROM
                (SELECT BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT, SUM(T.AMOUNT) AS T_AMOUNT
                FROM WISE_MONEY.BUDGET_MANAGEMENT BM
                INNER JOIN TRANSACTIONS T ON BM.CATEGORY_ID = T.CATEGORY_ID
                WHERE BM.AMOUNT > 0 AND BM.TYPE_ALLOCATION = 'LBP' AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                GROUP BY BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT) SUB
                GROUP BY USER_ID),
                TOTAL_BUDGET AS (SELECT B.USER_ID, COALESCE(AMOUNT, 0) + COALESCE(TR, 0) - COALESCE(TD, 0) - COALESCE(TE.TOTAL, 0) AS TOTAL
                FROM BUDGET B
                LEFT JOIN REVENU R ON R.USER_ID = B.USER_ID
                LEFT JOIN DEPENSES_LBP DL ON DL.USER_ID = B.USER_ID
                LEFT JOIN TOTAL_EXCES TE ON TE.USER_ID = B.USER_ID)
                SELECT *
                FROM (SELECT ID AS parentId, name, ROUND(SUM(TOTAL_TRANSACTIONS)/SUM(TOTAL_BM)*100,0) AS total, SUM(TOTAL_UP) AS COUNT, SUM(TOTAL_TRANSACTIONS) AS TRANSACTIONS, SUM(TOTAL_BM) AS BUDGET
                FROM (SELECT C2.ID, C2.NAME, C.ID AS CHILD_ID, C.NAME AS CHILD_NAME, SUM(T.AMOUNT) AS TOTAL_TRANSACTIONS, SUM(CASE WHEN BM.AMOUNT > 0 THEN 1 ELSE 0 END) TOTAL_UP,
                CASE WHEN TYPE_ALLOCATION = 'LBP' THEN GREATEST(BM.AMOUNT, SUM(T.AMOUNT)) ELSE ROUND(TB.TOTAL * BM.AMOUNT / 100, 0) END TOTAL_BM
                FROM WISE_MONEY.TRANSACTIONS T
                INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
                INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
                INNER JOIN WISE_MONEY.CATEGORIES C2 ON C2.ID = C.PARENT_ID
                INNER JOIN TOTAL_BUDGET TB ON TB.USER_ID = T.USER_ID
                WHERE BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                GROUP BY C2.ID, C2.NAME, TYPE_ALLOCATION, TB.TOTAL, BM.AMOUNT, C.ID, C.NAME
                UNION
                SELECT C2.ID, C2.NAME, C.ID, C.NAME, 0, SUM(CASE WHEN BM.AMOUNT > 0 THEN 1 ELSE 0 END) TOTAL_UP,
                CASE WHEN TYPE_ALLOCATION = 'LBP' THEN BM.AMOUNT ELSE ROUND(TB.TOTAL * BM.AMOUNT / 100, 0) END
                FROM WISE_MONEY.TRANSACTIONS T
                INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
                INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
                INNER JOIN WISE_MONEY.CATEGORIES C2 ON C2.ID = C.PARENT_ID
                INNER JOIN TOTAL_BUDGET TB ON TB.USER_ID = T.USER_ID
                WHERE BM.USER_ID = :userId AND BM.AMOUNT > 0 AND BM.CATEGORY_ID NOT IN (SELECT CATEGORY_ID FROM wise_money.transactions WHERE USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()))
                GROUP BY C2.ID, C2.NAME, C.ID, C.NAME, TB.TOTAL, TYPE_ALLOCATION, BM.AMOUNT) SUB
                GROUP BY ID, NAME) SUB2
                WHERE TOTAL > 0;
                """, nativeQuery = true)
    List<ParentSpendView> findParentSpendViewByUserId(@Param("userId") Long userId);

    @Query(value="""
                WITH BUDGET AS (SELECT USER_ID, AMOUNT FROM WISE_MONEY.BUDGETS
                WHERE USER_ID = :userId AND MONTH = EXTRACT(MONTH FROM SYSDATE()) AND YEAR = EXTRACT(YEAR FROM SYSDATE())),
                REVENU AS (SELECT T.USER_ID, SUM(AMOUNT) AS TR
                FROM WISE_MONEY.TRANSACTIONS T
                INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
                WHERE T.USER_ID = :userId
                AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                AND C.TYPE = 'REVENU'
                GROUP BY USER_ID),
                DEPENSES_LBP AS (SELECT BM.USER_ID, SUM(T.AMOUNT) AS TD FROM WISE_MONEY.TRANSACTIONS T
                INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
                WHERE BM.AMOUNT = 0
                AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                GROUP BY BM.USER_ID),
                TOTAL_EXCES AS (SELECT USER_ID, SUM(T_AMOUNT - AMOUNT) AS TOTAL
                FROM
                (SELECT BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT, SUM(T.AMOUNT) AS T_AMOUNT
                FROM WISE_MONEY.BUDGET_MANAGEMENT BM
                INNER JOIN TRANSACTIONS T ON BM.CATEGORY_ID = T.CATEGORY_ID
                WHERE BM.AMOUNT > 0 AND BM.TYPE_ALLOCATION = 'LBP' AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                GROUP BY BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT) SUB
                GROUP BY USER_ID),
                TOTAL_BUDGET AS (SELECT B.USER_ID, COALESCE(AMOUNT, 0) + COALESCE(TR, 0) - COALESCE(TD, 0) - COALESCE(TE.TOTAL, 0) AS TOTAL
                FROM BUDGET B
                LEFT JOIN REVENU R ON R.USER_ID = B.USER_ID
                LEFT JOIN DEPENSES_LBP DL ON DL.USER_ID = B.USER_ID
                LEFT JOIN TOTAL_EXCES TE ON TE.USER_ID = B.USER_ID)
                SELECT CATEGORY_ID AS childId, name, TOTAL_TRANSACTIONS AS TOTAL, TOTAL_BM AS budget, ROUND(TOTAL_TRANSACTIONS/TOTAL_BM * 100, 0) AS percent, BUDGET_AMOUNT AS AMOUNT
                FROM (SELECT T.CATEGORY_ID, C.NAME, SUM(T.AMOUNT) AS TOTAL_TRANSACTIONS, BM.AMOUNT AS BUDGET_AMOUNT,
                CASE WHEN TYPE_ALLOCATION = 'LBP' THEN GREATEST(BM.AMOUNT, SUM(T.AMOUNT)) ELSE ROUND(TB.TOTAL * BM.AMOUNT / 100, 0) END TOTAL_BM
                FROM WISE_MONEY.TRANSACTIONS T
                INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
                INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
                INNER JOIN TOTAL_BUDGET TB ON TB.USER_ID = T.USER_ID
                WHERE C.PARENT_ID = :parentId AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
                GROUP BY T.CATEGORY_ID, BM.AMOUNT, TYPE_ALLOCATION, TB.TOTAL) SUB;
                """, nativeQuery = true)
    List<ChildPercentView> findChildrenSpendViewByUserId(@Param("userId") Long userId, @Param("parentId") Long parentId);

        @Query(value="""
        WITH BUDGET AS (SELECT USER_ID, AMOUNT FROM WISE_MONEY.BUDGETS
        WHERE USER_ID = :userId AND MONTH = EXTRACT(MONTH FROM SYSDATE()) AND YEAR = EXTRACT(YEAR FROM SYSDATE())),
        REVENU AS (SELECT T.USER_ID, SUM(AMOUNT) AS TR
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId
        AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        AND C.TYPE = 'REVENU'
        GROUP BY USER_ID),
        DEPENSES_LBP AS (SELECT BM.USER_ID, SUM(T.AMOUNT) AS TD FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
        WHERE BM.AMOUNT = 0
        AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        GROUP BY BM.USER_ID),
        TOTAL_EXCES AS (SELECT USER_ID, SUM(T_AMOUNT - AMOUNT) AS TOTAL
        FROM
        (SELECT BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT, SUM(T.AMOUNT) AS T_AMOUNT
        FROM WISE_MONEY.BUDGET_MANAGEMENT BM
        INNER JOIN TRANSACTIONS T ON BM.CATEGORY_ID = T.CATEGORY_ID
        WHERE BM.AMOUNT > 0 AND BM.TYPE_ALLOCATION = 'LBP' AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        GROUP BY BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT) SUB
        GROUP BY USER_ID),
        TOTAL_BUDGET AS (SELECT B.USER_ID, COALESCE(AMOUNT, 0) + COALESCE(TR, 0) - COALESCE(TD, 0) - COALESCE(TE.TOTAL, 0) AS TOTAL
        FROM BUDGET B
        LEFT JOIN REVENU R ON R.USER_ID = B.USER_ID
        LEFT JOIN DEPENSES_LBP DL ON DL.USER_ID = B.USER_ID
        LEFT JOIN TOTAL_EXCES TE ON TE.USER_ID = B.USER_ID),
        TOTAL_LBP AS (SELECT USER_ID, SUM(TOTAL) AS TOTAL
        FROM(SELECT T.USER_ID, T.CATEGORY_ID, GREATEST(SUM(T.AMOUNT), BM.AMOUNT) AS TOTAL
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId AND BM.TYPE_ALLOCATION = 'LBP'
        AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        GROUP BY T.USER_ID, T.CATEGORY_ID, BM.AMOUNT
        UNION
        SELECT BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT
        FROM WISE_MONEY.BUDGET_MANAGEMENT BM
        WHERE BM.USER_ID = :userId AND BM.AMOUNT > 0 AND BM.TYPE_ALLOCATION = 'LBP' AND BM.CATEGORY_ID NOT IN (SELECT CATEGORY_ID FROM wise_money.transactions WHERE USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()))) SUB
        GROUP BY USER_ID),
        TOTAL_PERCENT AS (SELECT USER_ID, SUM(TOTAL) AS TOTAL
        FROM (SELECT T.USER_ID, T.CATEGORY_ID, GREATEST(CASE WHEN T.CATEGORY_ID IN (SELECT CATEGORY_ID FROM wise_money.transactions WHERE USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())) THEN (SELECT SUM(AMOUNT) FROM TRANSACTIONS WHERE USER_ID = 1 AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()) AND CATEGORY_ID = T.CATEGORY_ID) ELSE 0 END, ROUND(TB.TOTAL * BM.AMOUNT / 100, 0)) AS TOTAL
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
        INNER JOIN TOTAL_BUDGET TB ON TB.USER_ID = BM.USER_ID
        WHERE T.USER_ID = :userId AND BM.TYPE_ALLOCATION = 'PERCENT'
        GROUP BY T.USER_ID, T.CATEGORY_ID, BM.AMOUNT, TB.TOTAL) SUB
        GROUP BY USER_ID)
        SELECT COALESCE(AMOUNT, 0) + COALESCE(TR, 0) - COALESCE(TL.TOTAL, 0) - COALESCE(TP.TOTAL, 0) AS EPARGNE
        FROM BUDGET B
        LEFT JOIN REVENU R ON R.USER_ID = B.USER_ID
        LEFT JOIN TOTAL_LBP TL ON TL.USER_ID = B.USER_ID
        LEFT JOIN TOTAL_PERCENT TP ON TP.USER_ID = B.USER_ID;
        """, nativeQuery = true)
        Integer getEpargneOfMonth(@Param("userId") Long userId);

        @Query(value="""
        WITH CURRENT_MONTH AS (SELECT T.USER_ID, COALESCE(SUM(AMOUNT),0) AS CURRENT_AMOUNT
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE())
        AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()) AND C.TYPE = 'DEPENSE'
        GROUP BY T.USER_ID),
        PAST_MONTH AS (SELECT T.USER_ID, COALESCE(SUM(AMOUNT), 1) AS PAST_AMOUNT
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId AND C.TYPE = 'DEPENSE' AND ((EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) - 1 AND EXTRACT(MONTH FROM SYSDATE()) != 1
        AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()))
        OR (EXTRACT(MONTH FROM SYSDATE()) = 1 AND EXTRACT(MONTH FROM TRANSACTION_DATE) = 12 AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()) - 1))
        GROUP BY T.USER_ID)
        SELECT CM.CURRENT_AMOUNT, ROUND(CM.CURRENT_AMOUNT * 100 / PM.PAST_AMOUNT - 100, 0) AS GAP
        FROM CURRENT_MONTH CM
        INNER JOIN PAST_MONTH PM ON PM.USER_ID = CM.USER_ID;
        """, nativeQuery = true)
        List<PercentGap> getGapOfMonth(@Param("userId") Long userId);

        @Query(value="""
        SELECT MONTH, YEAR, SUM(CASE WHEN TYPE = 'DEPENSE' THEN AMOUNT ELSE 0 END) AS EXPENSES, SUM(CASE WHEN TYPE = 'REVENU' THEN AMOUNT ELSE 0 END) AS REVENUES
        FROM (SELECT EXTRACT(MONTH FROM TRANSACTION_DATE) AS MONTH, EXTRACT(YEAR FROM TRANSACTION_DATE) AS YEAR, AMOUNT, TYPE
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId) SUB
        GROUP BY MONTH, YEAR;
        """, nativeQuery = true)
        List<StatisticsViews> getExpensesRevenuesDifference(@Param("userId") Long userId);

        @Query(value="""
        SELECT *
        FROM TRANSACTIONS
        WHERE USER_ID = :userId
        AND TRANSACTION_DATE >= :startDate and TRANSACTION_DATE < :endDate
        """, nativeQuery = true)
        List<Transaction> findByUserAndDateRange(@Param("userId") Long userId, @Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate);

        @Query(value="""
        WITH CURRENT_MONTH AS (SELECT CATEGORY_ID, NAME, SUM(AMOUNT) AS AMOUNT
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM NOW()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM NOW())
        GROUP BY NAME, CATEGORY_ID),
        PRIOR_MONTH AS (SELECT CATEGORY_ID, NAME, SUM(AMOUNT) AS AMOUNT
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId AND (EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM NOW()) - 1 AND EXTRACT(MONTH FROM NOW()) != 1 AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM NOW()))
        OR (EXTRACT(MONTH FROM TRANSACTION_DATE) = 12 AND EXTRACT(MONTH FROM NOW()) = 1 AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM NOW()) - 1)
        GROUP BY NAME, CATEGORY_ID)
        SELECT CM.NAME, CM.AMOUNT - PM.AMOUNT AS DELTA
        FROM CURRENT_MONTH CM
        INNER JOIN PRIOR_MONTH PM ON PM.CATEGORY_ID = CM.CATEGORY_ID
        WHERE CM.AMOUNT - PM.AMOUNT > 0
        ORDER BY 2 DESC LIMIT 3;
        """, nativeQuery = true)
        List<DeltaTransactions> findDeltaTransactions(@Param("userId") Long userId);

        @Query(value = """
        SELECT SUM(AVERAGE) AS TOTAL
        FROM (SELECT ROUND(SUM(AMOUNT) / (DATEDIFF(LAST_DAY(SYSDATE()), SYSDATE()) + 1), 0) AS AVERAGE
        FROM (SELECT AMOUNT
        FROM BUDGETS B
        WHERE B.USER_ID = :userId AND MONTH = EXTRACT(MONTH FROM SYSDATE()) AND YEAR = EXTRACT(YEAR FROM SYSDATE())
        UNION
        SELECT SUM(AMOUNT)
        FROM TRANSACTIONS T
        INNER JOIN CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE C.TYPE = 'REVENU' AND C.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE())
        AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        UNION
        SELECT SUM(AMOUNT) * (-1)
        FROM BUDGET_MANAGEMENT BM
        WHERE USER_ID = :userId AND FREQUENCY = 1
        UNION
        SELECT SUM(T.AMOUNT) * (-1)
        FROM TRANSACTIONS T
        INNER JOIN CATEGORIES C ON C.ID = T.CATEGORY_ID
        INNER JOIN BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = C.ID
        WHERE BM.FREQUENCY = 2 AND C.TYPE = 'DEPENSE' AND C.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE())
        AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()) AND DATE_FORMAT(TRANSACTION_DATE, '%m/%d/%Y') < DATE_FORMAT(SYSDATE(), '%m/%d/%Y'))SUB
        UNION
        SELECT SUM(T.AMOUNT) * (-1)
        FROM TRANSACTIONS T
        INNER JOIN CATEGORIES C ON C.ID = T.CATEGORY_ID
        INNER JOIN BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = C.ID
        WHERE BM.FREQUENCY = 2 AND C.TYPE = 'DEPENSE' AND C.USER_ID = :userId AND DATE_FORMAT(TRANSACTION_DATE, '%m/%d/%Y') = DATE_FORMAT(SYSDATE(), '%m/%d/%Y'))SUB2;
        """, nativeQuery = true)
        Integer getAverageDaily(@Param("userId") Long userId);

        @Query(value = """
        SELECT SUM(AMOUNT) AS TOTAL
        FROM TRANSACTIONS T
        INNER JOIN CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE C.TYPE = 'REVENU' AND C.USER_ID = :userId AND
        EXTRACT(MONTH FROM SYSDATE()) = EXTRACT(MONTH FROM TRANSACTION_DATE) AND EXTRACT(YEAR FROM SYSDATE()) = EXTRACT(YEAR FROM TRANSACTION_DATE);
        """, nativeQuery = true)
        Integer getSumRevenues(@Param("userId") Long userId);

        @Query(value = """
        SELECT SUM(AMOUNT) AS TOTAL
        FROM TRANSACTIONS T
        INNER JOIN CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE C.TYPE = 'DEPENSE' AND C.USER_ID = :userId AND
        EXTRACT(MONTH FROM SYSDATE()) = EXTRACT(MONTH FROM TRANSACTION_DATE) AND EXTRACT(YEAR FROM SYSDATE()) = EXTRACT(YEAR FROM TRANSACTION_DATE);
        """, nativeQuery = true)
        Integer getSumDepenses(@Param("userId") Long userId);

        @Query(value = """
        WITH BUDGET AS (SELECT USER_ID, AMOUNT FROM WISE_MONEY.BUDGETS
        WHERE USER_ID = :userId AND MONTH = EXTRACT(MONTH FROM SYSDATE()) AND YEAR = EXTRACT(YEAR FROM SYSDATE())),
        REVENU AS (SELECT T.USER_ID, SUM(AMOUNT) AS TR
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        WHERE T.USER_ID = :userId
        AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        AND C.TYPE = 'REVENU'
        GROUP BY USER_ID),
        DEPENSES_LBP AS (SELECT BM.USER_ID, SUM(T.AMOUNT) AS TD FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
        WHERE BM.AMOUNT = 0
        AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        GROUP BY BM.USER_ID),
        TOTAL_EXCES AS (SELECT USER_ID, SUM(T_AMOUNT - AMOUNT) AS TOTAL
        FROM
        (SELECT BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT, SUM(T.AMOUNT) AS T_AMOUNT
        FROM WISE_MONEY.BUDGET_MANAGEMENT BM
        INNER JOIN TRANSACTIONS T ON BM.CATEGORY_ID = T.CATEGORY_ID
        WHERE BM.AMOUNT > 0 AND BM.TYPE_ALLOCATION = 'LBP' AND BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        GROUP BY BM.USER_ID, BM.CATEGORY_ID, BM.AMOUNT) SUB
        GROUP BY USER_ID),
        TOTAL_BUDGET AS (SELECT B.USER_ID, COALESCE(AMOUNT, 0) + COALESCE(TR, 0) - COALESCE(TD, 0) - COALESCE(TE.TOTAL, 0) AS TOTAL
        FROM BUDGET B
        LEFT JOIN REVENU R ON R.USER_ID = B.USER_ID
        LEFT JOIN DEPENSES_LBP DL ON DL.USER_ID = B.USER_ID
        LEFT JOIN TOTAL_EXCES TE ON TE.USER_ID = B.USER_ID)
        SELECT SUM(TOTAL_BM - TOTAL_TRANSACTIONS) AS TOTAL
        FROM (SELECT C2.ID, C2.NAME, C.ID AS CHILD_ID, C.NAME AS CHILD_NAME, SUM(T.AMOUNT) AS TOTAL_TRANSACTIONS,
        CASE WHEN TYPE_ALLOCATION = 'LBP' THEN GREATEST(BM.AMOUNT, SUM(T.AMOUNT)) ELSE GREATEST(SUM(T.AMOUNT),ROUND(TB.TOTAL * BM.AMOUNT / 100, 0)) END TOTAL_BM
        FROM WISE_MONEY.TRANSACTIONS T
        INNER JOIN WISE_MONEY.BUDGET_MANAGEMENT BM ON BM.CATEGORY_ID = T.CATEGORY_ID
        INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = T.CATEGORY_ID
        INNER JOIN WISE_MONEY.CATEGORIES C2 ON C2.ID = C.PARENT_ID
        INNER JOIN TOTAL_BUDGET TB ON TB.USER_ID = T.USER_ID
        WHERE BM.USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())
        GROUP BY C2.ID, C2.NAME, TYPE_ALLOCATION, TB.TOTAL, BM.AMOUNT, C.ID, C.NAME
        UNION
        SELECT C2.ID, C2.NAME, C.ID AS CHILD_ID, C.NAME AS CHILD_NAME, 0, CASE WHEN TYPE_ALLOCATION = 'LBP' THEN BM.AMOUNT ELSE GREATEST(CASE WHEN T.CATEGORY_ID IN (SELECT CATEGORY_ID FROM wise_money.transactions WHERE USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE())) THEN (SELECT SUM(AMOUNT) FROM TRANSACTIONS WHERE USER_ID = 1 AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()) AND CATEGORY_ID = T.CATEGORY_ID) ELSE 0 END,ROUND(TB.TOTAL * BM.AMOUNT / 100, 0)) END TOTAL_BM
        FROM WISE_MONEY.BUDGET_MANAGEMENT BM
	INNER JOIN WISE_MONEY.CATEGORIES C ON C.ID = BM.CATEGORY_ID
	INNER JOIN WISE_MONEY.CATEGORIES C2 ON C2.ID = C.PARENT_ID
	LEFT JOIN WISE_MONEY.TRANSACTIONS T ON T.CATEGORY_ID = BM.CATEGORY_ID
	INNER JOIN TOTAL_BUDGET TB ON TB.USER_ID = BM.USER_ID
        WHERE BM.USER_ID = :userId AND BM.AMOUNT > 0 AND BM.CATEGORY_ID NOT IN (SELECT CATEGORY_ID FROM wise_money.transactions WHERE USER_ID = :userId AND EXTRACT(MONTH FROM TRANSACTION_DATE) = EXTRACT(MONTH FROM SYSDATE()) AND EXTRACT(YEAR FROM TRANSACTION_DATE) = EXTRACT(YEAR FROM SYSDATE()))
        GROUP BY C2.ID, C.ID, BM.TYPE_ALLOCATION, BM.AMOUNT, TB.TOTAL) SUB;
        """, nativeQuery = true)
        Integer getSumDepFuture(@Param("userId") Long userId);
}
